# Run full cycle: login as internal -> get Valley Creek tenant/assessment -> call Claude document-requests.
# Prerequisites: docker compose up; run run-agent-demo.ps1 first so agent data is in Ingest.
# Usage: .\scripts\run-full-cycle.ps1

$ErrorActionPreference = "Stop"
$Base = "http://localhost:8000/api/v1"
$AdminEmail = "admin@summitrange.com"
$AdminPassword = "Admin1234!"

Write-Host "1. Login as internal user..."
$loginBody = @{ email = $AdminEmail; password = $AdminPassword } | ConvertTo-Json
$loginResp = Invoke-RestMethod -Uri "$Base/auth/login" -Method Post -Body $loginBody -ContentType "application/json"
$token = $loginResp.access_token
if (-not $token) { Write-Error "No token received" }

$headers = @{
    "Authorization" = "Bearer $token"
    "Content-Type"  = "application/json"
}

Write-Host "2. Get tenants (find Valley Creek)..."
$tenants = Invoke-RestMethod -Uri "$Base/tenants" -Headers $headers -Method Get
$vc = $tenants | Where-Object { $_.name -like "*Valley Creek*" } | Select-Object -First 1
if (-not $vc) { Write-Error "Valley Creek tenant not found. Run seed." }
$tenantId = $vc.id
Write-Host "   Tenant: $($vc.name) (id=$tenantId)"

Write-Host "3. Get assessments..."
$assessments = Invoke-RestMethod -Uri "$Base/tenants/$tenantId/assessments" -Headers $headers -Method Get
$assess = $assessments | Select-Object -First 1
if (-not $assess) { Write-Error "No assessment for tenant. Create one in the portal." }
$assessmentId = $assess.id
Write-Host "   Assessment: $assessmentId (status=$($assess.status))"

Write-Host "4. Call Claude document-requests (run engine + create notifications)..."
$resp = Invoke-RestMethod -Uri "$Base/tenants/$tenantId/assessments/$assessmentId/claude/document-requests" -Headers $headers -Method Post -Body "{}" -ContentType "application/json"
$n = $resp.notifications_created
Write-Host "   Notifications created: $n"
if ($resp.requests -and $resp.requests.Count -gt 0) {
    Write-Host "   Requests:"
    $resp.requests | ForEach-Object { Write-Host "     - $($_.control_code): $($_.reason)" }
}

Write-Host ""
if ($n -gt 0) {
    Write-Host "Client (client@valleycreek.example.com / Client2024!) will see $n new notification(s) in the portal bell."
} else {
    Write-Host "No document requests from Claude (either sufficient evidence in context or ANTHROPIC_API_KEY not set in backend .env)."
}

Write-Host "5. Create report package..."
$createBody = "{}"
$pkg = Invoke-RestMethod -Uri "$Base/tenants/$tenantId/assessments/$assessmentId/reports/packages" -Headers $headers -Method Post -Body $createBody -ContentType "application/json"
$packageId = $pkg.id
Write-Host "   Package: $packageId (version=$($pkg.package_version))"

Write-Host "6. Generate report (with Claude AI narrative if key set)..."
$genBody = '{"include_ai_summary":true,"ai_tone":"neutral"}'
Invoke-RestMethod -Uri "$Base/tenants/$tenantId/reports/packages/$packageId/generate" -Headers $headers -Method Post -Body $genBody -ContentType "application/json" | Out-Null
Write-Host "   Generated."

Write-Host "7. Publish package..."
$pubBody = '{"publish_note":"Full cycle script"}'
Invoke-RestMethod -Uri "$Base/tenants/$tenantId/reports/packages/$packageId/publish" -Headers $headers -Method Post -Body $pubBody -ContentType "application/json" | Out-Null
Write-Host "   Published."

Write-Host ""
Write-Host "Done. Download the report in Client portal (Reports) or Internal -> Reports."
Write-Host "In the PDF Executive Summary look for: 'This summary was generated by Claude AI from your questionnaire...'"
